'use client'

import { Geist, Geist_Mono } from "next/font/google";
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import "@fortawesome/fontawesome-free/css/all.min.css"
import { ToastContainer } from "react-toastify";
import "./globals.css";
import NavgationBar from "./components/NavgationBar";
import BottomBar from "./components/BottomBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 /* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 
 */
export default function RootLayout({ children }) {
// Then use it like:
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavgationBar/>
            <main>
            {children}
            </main>
            <ToastContainer position="top-right" 
              autoClose={5000} hideProgressBar={false} 
              newestOnTop={false} closeOnClick={false} 
              rtl={false} pauseOnFocusLoss draggable 
              pauseOnHover theme="light"
            />
          <BottomBar/>
      </body>
    </html>
  );
}
